version: '3.8'

services:
  web:
    build: ./app
    command: gunicorn -b 0.0.0.0:8000 backend.wsgi
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fintool_dev
      - POSTGRES_PASSWORD=fintool_dev
      - POSTGRES_DB=fintool

volumes:
  postgres_data:
