version: '3.8'

services:
  web:
    build: ./app
    command: gunicorn -b 0.0.0.0:8000 backend.wsgi
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

